# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Populando Posto/Graduacao
PostoGraduacao.create(:name => 'MA')
PostoGraduacao.create(:name => 'TB')
PostoGraduacao.create(:name => 'MB')
PostoGraduacao.create(:name => 'BR')
PostoGraduacao.create(:name => 'CL')
PostoGraduacao.create(:name => 'TC')
PostoGraduacao.create(:name => 'MJ')
PostoGraduacao.create(:name => 'CP')
PostoGraduacao.create(:name => '1T')
PostoGraduacao.create(:name => '2T')
PostoGraduacao.create(:name => 'AP')
PostoGraduacao.create(:name => 'SO')
PostoGraduacao.create(:name => '1S')
PostoGraduacao.create(:name => '2S')
PostoGraduacao.create(:name => '3S')
PostoGraduacao.create(:name => 'TM')
PostoGraduacao.create(:name => 'CB')
PostoGraduacao.create(:name => 'T1')
PostoGraduacao.create(:name => 'T2')
PostoGraduacao.create(:name => 'S1')
PostoGraduacao.create(:name => 'S2')
PostoGraduacao.create(:name => 'ALUNO CESD')
PostoGraduacao.create(:name => 'SE')
PostoGraduacao.create(:name => 'CV OF')
PostoGraduacao.create(:name => 'CV GRAD')
PostoGraduacao.create(:name => 'CV PRAÇA')
PostoGraduacao.create(:name => 'GEN BDA')
PostoGraduacao.create(:name => 'PM')

# Populando Especialidade
Especialidade.create(:nome => 'AL CESD')
Especialidade.create(:nome => 'ANS')
Especialidade.create(:nome => 'ANV')
Especialidade.create(:nome => 'ARM')
Especialidade.create(:nome => 'ASS')
Especialidade.create(:nome => 'AV')
Especialidade.create(:nome => 'BCO')
Especialidade.create(:nome => 'BCT')
Especialidade.create(:nome => 'BEI')
Especialidade.create(:nome => 'BEI 01')
Especialidade.create(:nome => 'BEI 02')
Especialidade.create(:nome => 'AL CESD')
Especialidade.create(:nome => 'AL CESD')
Especialidade.create(:nome => 'AL CESD')
Especialidade.create(:nome => 'AL CESD')
Especialidade.create(:nome => 'AL CESD')
Especialidade.create(:nome => 'AL CESD')
Especialidade.create(:nome => 'AL CESD')
Especialidade.create(:nome => 'AL CESD')
Especialidade.create(:nome => 'AL CESD')
Especialidade.create(:nome => 'AL CESD')
Especialidade.create(:nome => 'AL CESD')
Especialidade.create(:nome => 'AL CESD')
Especialidade.create(:nome => 'AL CESD')
Especialidade.create(:nome => 'AL CESD')


